### PR TITLE
Add config for rosmo

### PR DESCRIPTION
**Pull request by samuk**
I just added a Rosmo config here https://github.com/rosmo-robot/linorobot2_hardware/commit/f69188046b7a8e64cb08d40451352cd28943f120

& added a section at the bottom of platformio.ini

### CODE REVIEW

**Comment by hippo5329** [comment]
Thank you.

**Comment by hippo5329** [comment]
Hi, Sam, 

I checked again your code. There are some minor issues. I have to revert the merge and hard reset to earlier. Please modify and submit PR again.

Please change USE_ROSMO_CONFIG to USE_ROSMO_WIFI_CONFIG in platformio.ini .

Please rename your config file to rosms_wifi_config.h and change ESP32S3_WIFI_CONFIG_H to ROSMO_WIFI_CONFIG_H in your config.

Please include the updated config.h with your USE_ROSMO_WIFI_CONFIG.

Thanks.

- Thomas

**Comment by samuk** [comment]
Gah sorry about that.

I made all the changes, up to your last line "Please include the updated config.h with your USE_ROSMO_WIFI_CONFIG."

Could you explain this a bit more? I'm sorry I don't understand.

Thanks

Sam

**Comment by hippo5329** [comment]
Please check the wiki,

https://github.com/hippo5329/linorobot2_hardware/wiki#custom-configuration-file---recommended

**Pull request merged**
